### PR TITLE
[v4] Use op-sqlite

### PR DESCRIPTION
**Pull request by craftzdog**
- https://github.com/OP-Engineering/op-sqlite
- Get rid of the websql adapter and directly call SQLite APIs via op-sqlite
- Better performance
- New arch support

### CODE REVIEW

**Comment by craftzdog** [comment]
You can try [4.0.0-rc.1](https://www.npmjs.com/package/pouchdb-adapter-react-native-sqlite/v/4.0.0-rc.1)

**Comment by gabrielgrover** [comment]
@craftzdog Do you have suggestions for projects that use expo?  At my work we use this package at version 3, but we use it with expo sqlite since we are in a managed workflow.

**Comment by martin-ecatch** [comment]
@gabrielgrover FYI: op-sqlite works out of the box in Expo managed workflow. Just install op-sqlite and v4 of this plugin. Then build a development build of your app. Everything should work.
You can even use a pre-existing database - let me know if you need some advice on that.

**Comment by gabrielgrover** [comment]
> @gabrielgrover FYI: op-sqlite works out of the box in Expo managed workflow. Just install op-sqlite and v4 of this plugin. Then build a development build of your app. Everything should work. You can even use a pre-existing database - let me know if you need some advice on that.

Thanks @martin-ecatch !  Gonna try this out today.

**Comment by gabrielgrover** [comment]
@martin-ecatch So I installed opsqlite and version 4.0.5 of this package.  When i try to run my app I get the following error screen

Screenshot 2024-08-20 at 11 52 00 AM

here is my pouch config

```typescript
import HttpPouch from 'pouchdb-adapter-http';
import SQLiteAdapter from 'pouchdb-adapter-react-native-sqlite';
import PouchDB from 'pouchdb-core';
import PouchdbFind from 'pouchdb-find';
import mapreduce from 'pouchdb-mapreduce';
import replication from 'pouchdb-replication';

export const pouch_db = PouchDB.plugin(SQLiteAdapter)
  .plugin(HttpPouch)
  .plugin(mapreduce)
  .plugin(replication)
  .plugin(PouchdbFind);

```

**Comment by martin-ecatch** [comment]
@gabrielgrover I don't see anything wrong with your setup. To make sure:
- Are the libraries in your package.json? (npm does that automatically now, not sure about yarn)
- Did you build a new development build using EAS after installing the libraries?
- Are you using the latest SDK (51)?
- Note that this won't work in Expo Go. You need to ditch Expo Go and use development builds.
Hope this helps.

**Comment by gabrielgrover** [comment]
> @gabrielgrover I don't see anything wrong with your setup. To make sure:
> 
> * Are the libraries in your package.json? (npm does that automatically now, not sure about yarn)
> * Did you build a new development build using EAS after installing the libraries?
> * Are you using the latest SDK (51)?
> * Note that this won't work in Expo Go. You need to ditch Expo Go and use development builds.
>   Hope this helps.

Ah.  Yes I definitely was using expo go.  Will try a dev build

**Pull request merged**
