### PR TITLE
[WIP] Add tests

### PR DESCRIPTION
**Pull request by ewnd9**
I've tried to incorporate similar testing approach from [`pouchdb-react-native`](https://github.com/stockulus/pouchdb-react-native), but it turned out [`react-native-sqlite-storage`](https://github.com/andpor/react-native-sqlite-storage) can't be mocked. 

The only way I see is to test on devices / emulators, but I don't have experience with it. 

What do you think? Are you interested in testing with `pouchdb` tests?

### CODE REVIEW

**Comment by noradaiko** [comment]
Thanks for your PR and I would be glad to add tests!
It may be possible to reuse the tests of `pouchdb-adapter-websql-core`.

**Comment by ewnd9** [comment]
[`pouchdb`](https://github.com/pouchdb/pouchdb) repo uses a single test base, where different adapters are switched by environment variables in test matrix in [`travis-ci`](https://github.com/pouchdb/pouchdb/blob/master/.travis.yml), so there is no specific tests for `pouchdb-adapter-websql-core`

**Comment by noradaiko** [comment]
It looks like the tests can't run on iOS simulator because they depend on node.js.
I think `react-native-sqlite-storage` shouldn't be mocked because the main purpose of the test is to make sure its stability and compatibility with pouchdb.

**Comment by noradaiko** [comment]
Maybe we can pick tests from `pouchdb/tests/integration/` after removing dependencies on node.js.

**Comment by ewnd9** [comment]
Node.js shouldn't the case since pouchdb is tested in browsers too (via [sauce labs](https://github.com/pouchdb/pouchdb/blob/master/.travis.yml#L83-L87))

**Comment by noradaiko** [comment]
Sorry I forgot to mention that though, unfortunately mocha doesn't work inside React Native app.
mocha is used outside of the app in every use case I found.

**Pull request closed without merging**
